Glimpses_of_reasoning=["mistake detected",
"error in previous step",
"incorrect assumption",
"wait, actually",
"no, that’s wrong",
"revising my answer",
"adjusting for accuracy",
"reconsidering the initial point",
"that was inaccurate",
"upon review",
"let me clarify",
"assuming that",
"if we posit",
"given the premise",
"let’s assume",
"let’s try",
"hypothetically",
"under the condition",
"to be precise",
"specifically",
"meaning that",
"in explicit terms",
"strictly speaking",
"breaking it down further",
"to clarify",
"on the other hand",
"this depends on",
"a caveat here is",
"uncertainty arises because",
"if we suppose",
"mistake",
"error",
"incorrect",
"wait",
"actually, no",
"no, that's wrong",
"revising my answer",
"adjusting for accuracy",
"reconsidering the initial point",
"that was inaccurate",
"upon review",
"assuming that",
"if we posit",
"given the premise",
"hypothetically",
"under the condition",
"to be precise",
"specifically",
"meaning that",
"in explicit terms"]
Glimpses_of_reasoning=[]